name = "assign"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
account_id = "601e633d0760414f69ae040c7171af4c"
assets = { directory = ".open-next/assets", binding = "ASSETS" }
